[package]
name = "sudoku_solver"
version = "0.1.0"
authors = ["meven"]

[profile.release]
#debug = true
#lto = false

[dependencies]
time = "0.1.35"
num_cpus = "1.0"
error-chain = "0.10.0"
rayon = "1.0.0"
structopt = "0.2"
