[package]
name = "sudoku_solver"
version = "0.1.0"
authors = ["meven"]

[profile.release]
#debug = true
#lto = false

[dependencies]
time = "0.3.15"
num_cpus = "1.0"
error-chain = "0.12.4"
rayon = "1.0.0"
clap = { version = "4.0.17", features = ["derive"] }
